Repository jd-opensource/joylive-agent, pull requests merged in 2024-12, with the labels that each got.

#165 Add version to register
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/Constants.java
  joylive-plugin/joylive-registry/joylive-registry-springcloud3/src/main/java/com/jd/live/agent/plugin/registry/springcloud/v3/interceptor/RegistryInterceptor.java
Labels: enhancement

#168 Support default lane space.
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/cache/Cache.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/instance/Endpoint.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/LaneFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/LaneMetadata.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/parser/LaneMetadataParser.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/GovernancePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/lane/LaneSpace.java
  joylive-package/src/main/assembly/config/lanes.json
Labels: enhancement

#159 springcloud3 support exception name CircuitBreak
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/Constants.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/exception/ErrorPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/CircuitBreakerFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/AbstractHttpResponse.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/ServiceResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/pom.xml
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/definition/ExceptionCarryingDefinition.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/interceptor/ExceptionCarryingInterceptor.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/resources/META-INF/services/com.jd.live.agent.core.plugin.definition.PluginDefinition
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/cluster/GatewayCluster.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/response/GatewayClusterResponse.java
Labels: enhancement

#175 Optimize invoke origin method
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/advice/AdviceHandler.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/advice/AdviceKey.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/context/ExecutableContext.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/context/LockContext.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/context/MethodContext.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/context/OriginStack.java
  joylive-implement/joylive-bytekit/joylive-bytekit-bytebuddy/src/main/java/com/jd/live/agent/implement/bytekit/bytebuddy/advice/MemberMethodAdvice.java
  joylive-implement/joylive-bytekit/joylive-bytekit-bytebuddy/src/main/java/com/jd/live/agent/implement/bytekit/bytebuddy/advice/StaticMethodAdvice.java
Labels: bug, enhancement

#178 exclude certain apps
  joylive-bootstrap/joylive-bootstrap-premain/src/main/java/com/jd/live/agent/bootstrap/LiveAgent.java
  joylive-package/src/main/assembly/config/bootstrap.properties
Labels: enhancement

#179 update shaded
  NOTICE
  joylive-implement/joylive-event/joylive-event-opentelemetry/pom.xml
Labels: bug

#184 Support W3C Baggage specification
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/TransmitConfig.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/context/LivePropagation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/context/Propagation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/context/W3cBaggagePropagation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/PolicyManager.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HeaderReader.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HeaderWriter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/MultiMapHeader.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/ObjectMapHeader.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/StringMapHeader.java
Labels: enhancement

#187 Routing by port
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/instance/Endpoint.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/RouteFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/PortFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HttpRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/Portable.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.RouteFilter
Labels: enhancement
