Repository jd-opensource/joylive-agent, pull requests merged in 2024-11, with the labels that each got.

#134 Service registration adds startup time, weight, and warm-up settings
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/Constants.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/AppService.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/Application.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/instance/Endpoint.java
  joylive-demo/joylive-demo-grpc/joylive-demo-grpc-service-api/pom.xml
  joylive-package/src/main/assembly/config/bootstrap.properties
  joylive-plugin/joylive-router/joylive-router-dubbo2.6/src/main/java/com/jd/live/agent/plugin/router/dubbo/v2_6/instance/DubboEndpoint.java
  joylive-plugin/joylive-router/joylive-router-dubbo2.7/src/main/java/com/jd/live/agent/plugin/router/dubbo/v2_7/instance/DubboEndpoint.java
  joylive-plugin/joylive-router/joylive-router-dubbo3/src/main/java/com/jd/live/agent/plugin/router/dubbo/v3/instance/DubboEndpoint.java
Labels: enhancement

#135 support fastjson2 parser
  joylive-implement/joylive-parser/joylive-parser-fastjson2/pom.xml
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/AbstractFastjson2Parser.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/Fastjson2JsonParser.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/Fastjson2YamlParser.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/JoyLiveReaderModule.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/JoyLiveWriterModule.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/ProxySupport.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/package-info.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/object/ProxyObjectReader.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/object/ProxyObjectWriter.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/ProxyTimeReader.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/ProxyTimeWriter.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/reader/ObjectReaderImplCalendarSZ.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/reader/ObjectReaderImplDateSZ.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/reader/ObjectReaderImplOffsetDateTimeSZ.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/reader/ObjectReaderImplOffsetTimeSZ.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/java/com/jd/live/agent/implement/parser/fastjson2/proxy/time/reader/ObjectReaderImplZonedDateTimeSZ.java
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/resources/META-INF/services/com.jd.live.agent.core.parser.ConfigParser
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/resources/META-INF/services/com.jd.live.agent.core.parser.JsonPathParser
  joylive-implement/joylive-parser/joylive-parser-fastjson2/src/main/resources/META-INF/services/com.jd.live.agent.core.parser.ObjectParser
  joylive-implement/joylive-parser/pom.xml
Labels: enhancement

#139 Add write protect methods config
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/Invocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/ServiceMetadata.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/parser/ServiceMetadataParser.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/cluster/RetryPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/live/ServiceLivePolicy.java
Labels: bug, enhancement

#152 shade nacos jar & fix service starting classloader
  joylive-core/joylive-core-framework/src/main/java/com/jd/live/agent/core/service/ServiceManager.java
  joylive-implement/joylive-service/joylive-service-nacos/pom.xml
  joylive-implement/joylive-service/joylive-service-nacos/src/main/java/com/jd/live/agent/implement/service/policy/nacos/LiveSpaceNacosSyncer.java
Labels: bug, enhancement

#154 If live is not enabled, there is no need to parse live metadata
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/InboundInvocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/Invocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/OutboundInvocation.java
Labels: enhancement

#161 Fix Feign's Response Headers to be Case-Insensitive
  joylive-plugin/joylive-router/joylive-router-springcloud2/src/main/java/com/jd/live/agent/plugin/router/springcloud/v2/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud2/src/main/java/com/jd/live/agent/plugin/router/springcloud/v2/response/FeignClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/FeignClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/FeignClusterResponse.java
Labels: bug
