Repository jd-opensource/joylive-agent, pull requests merged in 2024-10, with the labels that each got.

#73 Fix #72
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/ServicePolicy.java
Labels: bug

#74 Fix #42
  joylive-bom/pom.xml
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/exception/FaultException.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/fault/FaultInjection.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/fault/delay/DelayFaultInjection.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/fault/error/ErrorFaultInjection.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/OutboundFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/outbound/FaultInjectionFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/PolicyId.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/MergePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/ServicePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/fault/FaultInjectionPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/rule/ConditionalMatcher.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.fault.FaultInjection
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.OutboundFilter
  joylive-plugin/joylive-router/joylive-router-dubbo2.6/src/main/java/com/alibaba/dubbo/rpc/cluster/support/Dubbo26Cluster.java
  joylive-plugin/joylive-router/joylive-router-dubbo2.7/src/main/java/org/apache/dubbo/rpc/cluster/support/Dubbo27Cluster.java
  joylive-plugin/joylive-router/joylive-router-dubbo3/src/main/java/org/apache/dubbo/rpc/cluster/support/Dubbo3Cluster.java
  joylive-plugin/joylive-router/joylive-router-sofarpc/src/main/java/com/jd/live/agent/plugin/router/sofarpc/cluster/SofaRpcCluster.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/cluster/AbstractClientCluster.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/cluster/AbstractClientCluster.java
  pom.xml
Labels: enhancement

#81 Fix #80
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/bytekit/advice/AdviceHandler.java
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/plugin/definition/Interceptor.java
Labels: bug

#87 Fix #86
  joylive-bootstrap/joylive-bootstrap-api/src/main/java/com/jd/live/agent/bootstrap/exception/RejectException.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/InboundInvocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/Invocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/InvocationContext.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/OutboundInvocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/cluster/AbstractClusterInvoker.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/LoadBalanceFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/StickyFilter.java
  joylive-plugin/joylive-router/joylive-router-springweb5/src/main/java/com/jd/live/agent/plugin/router/springweb/v5/interceptor/HandlerAdapterInterceptor.java
  joylive-plugin/joylive-router/joylive-router-springweb6/src/main/java/com/jd/live/agent/plugin/router/springweb/v6/interceptor/HandlerAdapterInterceptor.java
Labels: bug

#89 Fix #88
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/GovernanceConfig.java
  joylive-package/src/main/assembly/config/config.yaml
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/definition/ServiceInstanceListSupplierDefinition.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/interceptor/ServiceInstanceListSupplierInterceptor.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/definition/ServiceInstanceListSupplierDefinition.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/interceptor/ServiceInstanceListSupplierInterceptor.java
  joylive-test/joylive-test-bytebuddy/src/test/resources/config/config.yaml
Labels: enhancement

#95 Fix #94
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/auth/Authenticate.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/auth/token/TokenAuthenticate.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/OutboundFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/AuthFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/ConcurrencyLimitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/FailoverFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/PermissionFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/RateLimitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/ReadyFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/UnitInFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/outbound/AuthFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HttpRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/RpcRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/ServiceRequest.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.InboundFilter
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.OutboundFilter
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.RouteFilter
Labels: bug, enhancement

#97 Fix #96
  NOTICE
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/CollectionUtils.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/http/HttpUtils.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/map/CaseInsensitiveLinkedMap.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/map/MultiLinkedMap.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/map/MultiMap.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/map/MultiMapAdapter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HttpRequest.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/request/FeignClusterRequest.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/request/FeignClusterRequest.java
Labels: bug

#99 Fix #98
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/AbstractRateLimiter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/RateLimiter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/leakybucket/LeakyBucketLimiter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/leakybucket/LeakyBucketLimiterFactory.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/leakybucket/LeakyBucketLimiterGroup.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/tokenbucket/SmoothTokenBucketLimiter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/ratelimit/tokenbucket/SmoothTokenBucketLimiterFactory.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/limit/AbstractLimitPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/limit/LimitPolicy.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.ratelimit.RateLimiterFactory
Labels: enhancement

#102 Supports query and cookie matching for RPC calls
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/util/type/ValuePath.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/AbstractTagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/TagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/cookie/CookieTagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/header/HeaderTagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/query/QueryTagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/system/ClientIpTagProvider.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/system/ConsumerTagProvider.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/system/SystemTagMatcher.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/matcher/system/SystemTagProvider.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/HttpRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/RpcRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/ServiceRequest.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.matcher.TagMatcher
Labels: bug, enhancement

#110 Fix null http response code
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/ReactiveClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/response/GatewayClusterResponse.java
Labels: bug

#112 Fix the issue where Spring Cloud Gateway gets a null response content when trying to judge the circuit breaker
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/cluster/GatewayCluster.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/response/GatewayClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springgateway4/src/main/java/com/jd/live/agent/plugin/router/springgateway/v4/cluster/GatewayCluster.java
  joylive-plugin/joylive-router/joylive-router-springgateway4/src/main/java/com/jd/live/agent/plugin/router/springgateway/v4/response/GatewayClusterResponse.java
Labels: bug

#114 Fix case sensitive issue of code policy match
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/exception/ErrorPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/cluster/FailoverClusterInvoker.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/CircuitBreakerFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/ServicePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/circuitbreak/CircuitBreakPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/cluster/ClusterPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/cluster/RetryPolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/service/exception/CodePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/Request.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/request/ServiceRequest.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/HttpResponse.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/ServiceResponse.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/cluster/GatewayCluster.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/request/GatewayClusterRequest.java
  joylive-plugin/joylive-router/joylive-router-springgateway4/src/main/java/com/jd/live/agent/plugin/router/springgateway/v4/cluster/GatewayCluster.java
  joylive-plugin/joylive-router/joylive-router-springgateway4/src/main/java/com/jd/live/agent/plugin/router/springgateway/v4/request/GatewayClusterRequest.java
Labels: bug

#117 Fix unit route without unit rule id
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/resources/META-INF/services/com.jd.live.agent.governance.invoke.filter.InboundFilter
Labels: bug

#119 118-fix-multi-live-space-routing-issue
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/AppService.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/Application.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/LiveConfig.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/ServiceConfig.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/interceptor/AbstractMessageInterceptor.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/InboundInvocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/Invocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/OutboundInvocation.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/InboundFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/FailoverFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/LaneFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/LiveMetadata.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/parser/LiveMetadataParser.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/GovernancePolicy.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/live/LiveSpace.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/policy/live/UnitRule.java
  joylive-implement/joylive-service/joylive-service-microservice/src/main/java/com/jd/live/agent/implement/service/policy/microservice/MicroServiceSyncer.java
  joylive-implement/joylive-service/joylive-service-multilive/src/main/java/com/jd/live/agent/implement/service/policy/multilive/LiveServiceSyncer.java
  joylive-implement/joylive-service/joylive-service-multilive/src/main/java/com/jd/live/agent/implement/service/policy/multilive/LiveSpaceSyncer.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo2.6/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v2_6/interceptor/ReferenceConfigInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo2.6/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v2_6/interceptor/ServiceConfigInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo2.7/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v2_7/interceptor/AppendRuntimeParametersInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo2.7/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v2_7/interceptor/RegistryInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo3/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v3/interceptor/ReferenceConfigInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo3/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v3/interceptor/RegistryInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-dubbo3/src/main/java/com/jd/live/agent/plugin/registry/dubbo/v3/interceptor/ServiceConfigInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-sofarpc/src/main/java/com/jd/live/agent/plugin/registry/sofarpc/interceptor/ConsumerBootstrapInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-sofarpc/src/main/java/com/jd/live/agent/plugin/registry/sofarpc/interceptor/ProviderBootstrapInterceptor.java
  joylive-plugin/joylive-registry/joylive-registry-springcloud3/src/main/java/com/jd/live/agent/plugin/registry/springcloud/v3/interceptor/RegistryInterceptor.java
Labels: bug

#121 1. none unit services prioritize routing to instances within the current space 2. fix liveless inbound error.
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/Application.java
  joylive-core/joylive-core-api/src/main/java/com/jd/live/agent/core/instance/Location.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/instance/Endpoint.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/CellAction.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/RouteTarget.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/inbound/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/GroupFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/TagRouteFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/UnitFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/LiveMetadata.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/parser/LiveMetadataParser.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/AbstractHttpResponse.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/response/HttpResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/FeignClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud3/src/main/java/com/jd/live/agent/plugin/router/springcloud/v3/response/ReactiveClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/BlockingClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/FeignClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springcloud4/src/main/java/com/jd/live/agent/plugin/router/springcloud/v4/response/ReactiveClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springgateway3/src/main/java/com/jd/live/agent/plugin/router/springgateway/v3/response/GatewayClusterResponse.java
  joylive-plugin/joylive-router/joylive-router-springgateway4/src/main/java/com/jd/live/agent/plugin/router/springgateway/v4/response/GatewayClusterResponse.java
Labels: bug, enhancement

#129 Support cluster first
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/LocalFirstMode.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/config/ServiceConfig.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/instance/Endpoint.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/RouteTarget.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/filter/route/CellFilter.java
  joylive-core/joylive-governance-api/src/main/java/com/jd/live/agent/governance/invoke/metadata/parser/ServiceMetadataParser.java
  joylive-package/src/main/assembly/config/config.yaml
Labels: enhancement
